routes/backend.php
<?php

Route::group(['middleware' => ['role:admin|manager']], function() {
    Route::get('changeStatus', 'UserController@ChangeUserStatus')->name('changeStatus');
    Route::post('changeStatus', 'UserController@ChangeUserStatus')->name('changeStatus');
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('formations','FormationController');
    Route::get('/profile1', 'AvatarController@index')->name('profile.show');
    Route::get('/admin','BackController@index')->name("backIndex");
    /* Events route */
    Route::resource('events', 'EventController');
    Route::resource('categories', 'CategoryController');

});

Route::get('/admin','BackEndController@index')->middleware('auth')->name("backIndex");
Route::get('/login','AuthBack\MyloginController@login')->name("login");
Route::post('/login','AuthBack\MyloginController@treatmentLogin')->name("tLogin");
Route::get('/logout','AuthBack\MyloginController@getOut')->name("logout");
Route::get('/logout','AuthBack\MyloginController@getOut1')->name("logout1");
Route::get('/signup','AuthBack\MysignupController@signup')->name("singup");
Route::post('/signup','AuthBack\MysignupController@treatmentSignup')->name("tSingup");
//Route::get('/addUser','BackController@addUser');
Route::get('/frontend', function () {
    return view('frontend.home');
});
//for language transcription
Route::get('languages', 'LanguageTranslationController@index')->name('languages');
Route::post('translations/update', 'LanguageTranslationController@transUpdate')->name('translation.update.json');
Route::post('translations/updateKey', 'LanguageTranslationController@transUpdateKey')->name('translation.update.json.key');
Route::delete('translations/destroy/{key}', 'LanguageTranslationController@destroy')->name('translations.destroy');
Route::post('translations/create', 'LanguageTranslationController@store')->name('translations.create');
Route::get('lang/{locale}', 'FrontController@lang');

routes/frontend.php
<?php

Route::get('/home','FrontController@index')->name('home');
Route::get('lang/{locale}', 'FrontController@lang'); //for Localisation
Route::get('/course_list','FrontController@formations_index')->name('course_list');
Route::get('check-translation', function(){
    \App::setLocale('fr');
    \Carbon\Carbon::setLocale('fr');
    dd(__('website'));
});
Route::group(['middleware' => ['role:learner']], function() {
    Route::get('/learner','LearnerController@index')->name("learner");
    Route::post('/inscription','LearnerController@inscription')->name("inscription");

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function (){
    return redirect('home');
});
//Auth::routes();

Route::get('/frontend', function () {
    return view('frontend.home');
});
Route::get('profile', 'AvatarController@index')->middleware('auth')->name('profile.show');
Route::resource('avatar','AvatarController')->middleware('auth');

Route::get('/admin1', function () {
    return view('backend.index');
});

//for language transcription
Route::get('languages', 'LanguageTranslationController@index')->name('languages');
Route::post('translations/update', 'LanguageTranslationController@transUpdate')->name('translation.update.json');
Route::post('translations/updateKey', 'LanguageTranslationController@transUpdateKey')->name('translation.update.json.key');
Route::delete('translations/destroy/{key}', 'LanguageTranslationController@destroy')->name('translations.destroy');
Route::post('translations/create', 'LanguageTranslationController@store')->name('translations.create');
Route::get('check-translation', function(){
    \App::setLocale('fr');
    dd(__('website'));
});

app/Http/Controllers/FrontEnd/FrontController.php
<?php

namespace App\Http\Controllers\FrontEnd;

use App\Category;
use App\Formation;
use App\Event;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Illuminate\Http\Request;
use MaddHatter\LaravelFullcalendar\Facades\Calendar;



class FrontController extends Controller
{
    public function index() //Request $request
    {
        $events = Event::orderBy('id','DESC')->get();
        $event = [];
        foreach ($events as $row){
            $enddate = $row->end_date."24:00:00";
            $event[]= \Calendar::event(
                $row->title,
                false,
                new \DateTime($row->start_date),
                new \DateTime($row->end_date),
                $row->id,
                [
                    'color' => $row->color,
                ]
            );
        }
        $calendar = \Calendar::addEvents($event);

        $carbon = Carbon::now()->subMinutes(2)->diffForHumans();
        //$s = $request->input('s');
        $categories = Category::latest()->take(3)->get();
        $formations = Formation::latest()->take(3)->get();
        return view("frontend.layouts.frontEndBase", compact('formations','calendar', 'categories', 'events', 'carbon'));
    }
    public function lang($locale)
    {
        \App::setLocale($locale);
        session()->put('locale', $locale);
        return redirect()->back();
    }

    public function formations_index(Request $request){
        $events = Event::all();
        $event = [];
        foreach ($events as $row){
            $enddate = $row->end_date."24:00:00";
            $event[]= \Calendar::event(
                $row->title,
                false,
                new \DateTime($row->start_date),
                new \DateTime($row->end_date),
                $row->id,
                [
                    'color' => $row->color,
                ]
            );
        }
        $calendar = \Calendar::addEvents($event);

        //$s = $request->input('s');
        $formations = Formation::all();
        //->search($s)->paginate(7);
        $categories = category::all();
        return view('frontend.courses.courses_index', compact('formations', 'categories', 'calendar')); //, 's'
    }
    
}

app/Http/Controllers/FrontEnd/LearnerController.php
<?php

namespace App\Http\Controllers\FrontEnd;

use App\Inscription;
use DateTime;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class LearnerController extends Controller
{
    function __construct()
    {
        $this->middleware('auth');
    }
    public function index(){
        $inscriptions = Inscription::orderBy('id','DESC')->get();
        return view('frontend.learner.dashboard', compact('inscriptions'));
    }
    /**
     * inscription to cources
     */
    public function inscription(Request $request){
        $lerner_id = Auth::id();
        $now = new DateTime('now');

        $inscription = new Inscription($request->all());
        $inscription->formation_id = $request->input('formation_id');
        $inscription->learner_id = $lerner_id;
        $inscription->date_inscription = $now;
        $inscription->save();
        return redirect(route('learner'));
        //return view('frontend.learner.dashboard')->with('success', 'Inscription réussit');
    }

}

resources/views/frontend/home.blade.php
@extends('frontend.layouts.frontEndBase')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/frontend/profile.blade.php
@extends("frontend.layouts.frontEndBase1")
@section('title', 'Update Profile')
@section('content')
<div class="container">
    <div class="row mb-5">
        <div class="container col-md-12 row">
            <br/>
        <div class="col-md-8 col-md-offset-1">
            <h2>Email: {{ $user->email }} </h2>

            @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> {{__('some_problem_with_input')}}.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif

            <br/>
            <form  action="{{ route('avatar.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="input-group">
                    <div class="col-xs-8 col-sm-8 col-md-8">
                        <div class="form-group">
                            <strong>{{__('name')}} : </strong>
                            {!! Form::text('name', $user->name, array('placeholder' => 'Name','class' => 'form-control')) !!}
                        </div>
                    </div>
                    <div class="col-xs-8 col-sm-8 col-md-8">
                        <div class="form-group">
                            <strong>{{__('birth_place')}} : </strong>
                            {!! Form::text('birth_place', $user->birth_place, array('placeholder' => 'Birth Place','class' => 'form-control')) !!}
                        </div>
                    </div>
                    <div class="col-xs-8 col-sm-8 col-md-8">
                        <div class="form-group">
                            <strong>{{__('global.phone')}} : </strong>
                            {!! Form::number('phone_number', $user->phone_number, array('placeholder' => 'Phone Number','class' => 'form-control')) !!}
                        </div>
                    </div>
                    <div class="col-xs-8 col-sm-8 col-md-8">
                        <div class="row form-group has-feedback">
                            <label for="gender">&nbsp;&nbsp;&nbsp;&nbsp;<strong>{{__('gender')}} : &nbsp;&nbsp;</strong>
                            </label>
                            {!! Form::select('gender', AppHelper::GENDER, $user->gender , ['class' => "form-control gender"]) !!}
                            <span class="form-control-feedback"></span>
                        </div>
                    </div>
                    <div class="col-xs-8 col-sm-8 col-md-8">
                        <div class="form-group">
                            <strong>{{__('dao_custom.birth_date')}} : </strong>
                            {!! Form::date('birth_date', $user->birth_date, array('placeholder' => 'Birth Date','class' => 'form-control')) !!}
                        </div>
                    </div>
                    <div class="col-xs-8 col-sm-8 col-md-8">
                        <div class="custom-file">
                            <input type="file" name="avatar" class="custom-file-input" id="inputGroupFile04" >
                            <label class="custom-file-label" for="inputGroupFile04">{{__('choose_file')}}</label>
                        </div>
                    </div>

                    <div class="input-group-append">
                        <input class="btn btn-success" type="submit" id="inputGroupFileAddon04" value="{{__('update')}}"  />
                    </div>
                </div>
            </form>
        </div>
        <div class="card-columns col-xs-3 col-sm-3 col-md-3">
            @foreach($avatars as $avatar)
                <div class="card" style="width: 13rem;">
                    <img src="{{$avatar->getUrl()}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ $user->email }}</h5>
                        <a href="#" class="text-danger align-content-center"><i class="fa fa-minus-circle fa-3x"></i></a>
                    </div>
                </div>
            @endforeach

        </div>
        </div>
    </div>
</div>
@endsection
@section('js')
    <script type="text/javascript">
        $(document).ready(function() {
            $('.gender').select2();
        });
    </script>
@endsection