routes/backend.php
<?php

Route::group(['middleware' => ['role:admin|manager']], function() {
    Route::get('changeStatus', 'UserController@ChangeUserStatus')->name('changeStatus');
    Route::post('changeStatus', 'UserController@ChangeUserStatus')->name('changeStatus');
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('formations','FormationController');
    Route::get('/profile1', 'AvatarController@index')->name('profile.show');
    Route::get('/admin','BackController@index')->name("backIndex");
    /* Events route */
    Route::resource('events', 'EventController');
    Route::resource('categories', 'CategoryController');

});

Route::get('/admin','BackEndController@index')->middleware('auth')->name("backIndex");
Route::get('/login','AuthBack\MyloginController@login')->name("login");
Route::post('/login','AuthBack\MyloginController@treatmentLogin')->name("tLogin");
Route::get('/logout','AuthBack\MyloginController@getOut')->name("logout");
Route::get('/logout','AuthBack\MyloginController@getOut1')->name("logout1");
Route::get('/signup','AuthBack\MysignupController@signup')->name("singup");
Route::post('/signup','AuthBack\MysignupController@treatmentSignup')->name("tSingup");
//Route::get('/addUser','BackController@addUser');
Route::get('/frontend', function () {
    return view('frontend.home');
});
//for language transcription
Route::get('languages', 'LanguageTranslationController@index')->name('languages');
Route::post('translations/update', 'LanguageTranslationController@transUpdate')->name('translation.update.json');
Route::post('translations/updateKey', 'LanguageTranslationController@transUpdateKey')->name('translation.update.json.key');
Route::delete('translations/destroy/{key}', 'LanguageTranslationController@destroy')->name('translations.destroy');
Route::post('translations/create', 'LanguageTranslationController@store')->name('translations.create');
Route::get('lang/{locale}', 'FrontController@lang');

routes/frontend.php
<?php

Route::get('/home','FrontController@index')->name('home');
Route::get('lang/{locale}', 'FrontController@lang'); //for Localisation
Route::get('/course_list','FrontController@formations_index')->name('course_list');
Route::get('check-translation', function(){
    \App::setLocale('fr');
    \Carbon\Carbon::setLocale('fr');
    dd(__('website'));
});
Route::group(['middleware' => ['role:learner']], function() {
    Route::get('/learner','LearnerController@index')->name("learner");
    Route::post('/inscription','LearnerController@inscription')->name("inscription");

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function (){
    return redirect('home');
});
//Auth::routes();

Route::get('/frontend', function () {
    return view('frontend.home');
});
Route::get('profile', 'AvatarController@index')->middleware('auth')->name('profile.show');
Route::resource('avatar','AvatarController')->middleware('auth');

Route::get('/admin1', function () {
    return view('backend.index');
});

//for language transcription
Route::get('languages', 'LanguageTranslationController@index')->name('languages');
Route::post('translations/update', 'LanguageTranslationController@transUpdate')->name('translation.update.json');
Route::post('translations/updateKey', 'LanguageTranslationController@transUpdateKey')->name('translation.update.json.key');
Route::delete('translations/destroy/{key}', 'LanguageTranslationController@destroy')->name('translations.destroy');
Route::post('translations/create', 'LanguageTranslationController@store')->name('translations.create');
Route::get('check-translation', function(){
    \App::setLocale('fr');
    dd(__('website'));
});

app/Http/Controllers/BackEnd/AuthBack/MyloginController.php
<?php

namespace App\Http\Controllers\BackEnd\AuthBack;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
//use MercurySeries\Flashy\Flashy;

class MyloginController extends Controller
{
    public function login()
    {
        $title="Login";
        return view('backend.pages.login',compact('title'));
    }

    public function treatmentLogin()
    {
        request()->validate([
           'email'=>['required','email'],
            'password'=>['required']
        ]);
        $resultat=auth()->attempt([
           'email'=>request('email'),
            'password'=>request('password')
        ]);
        if ($resultat){
            if (auth()->user()->hasRole('admin') || auth()->user()->hasRole('manager')){
                return redirect(route('backIndex'));
            }else{
               // Flashy::info('Heureux de vous revoir ');
                return redirect(route('home'));
            }
        }

        return back()->withInput()->withErrors([
            'email'=>'Vos identifiants sont incorects.'
        ]);
    }

    public function getOut1()
    {
        auth()->logout();
        return redirect(route('home'))->with("success", "Nous attendons votre retour");
    }
}

app/Http/Controllers/BackEnd/AuthBack/MysignupController.php
<?php

namespace App\Http\Controllers\BackEnd\AuthBack;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
//use App\Models\Utilisateur;
//use MercurySeries\Flashy\Flashy;

class MysignupController extends Controller
{
    public function signup()
    {
        $title="Sign Up";
        return view('backend.pages.register',compact('title'));
    }

    public function treatmentSignup()
    {
        //form Validation
        request()->validate([
            'email'=>['required','email'],
            'nom'=>['required'],
            'password'=>['required','confirmed'],
            'password_confirmation'=>['required']
        ]);

        $email_error = trans('dao_custum.email_no_available');

        $user=new User();
        $user->name=\request("nom");
        $user->email=\request("email");
        $user->password=bcrypt(\request("password"));
        try{
            $user->save();
        } catch (\Illuminate\Database\QueryException $exception){
            session()->flash('exist_email',"$email_error");
            return back()->withInput();
        }

        $resultat=auth()->attempt([
            'email'=>request('email'),
            'password'=>request('password')
        ]);
        if ($resultat){
            auth()->user()->assignRole("learner");
            if (auth()->user()->hasRole('admin') || auth()->user()->hasRole('manager')){
                return redirect(route('backIndex'));
            }else{
               // Flashy::info('Heureux de vous revoir ');
                return redirect(route('home'));
            }
        }


        return redirect(route('backIndex'));
    }
}

app/Http/Controllers/BackEnd/AvatarController.php
<?php

namespace App\Http\Controllers\BackEnd;

use App\Event;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AvatarController extends Controller
{
    function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = Event::orderBy('id','DESC')->get();
        $event = [];
        foreach ($events as $row){
            $enddate = $row->end_date."24:00:00";
            $event[]= \Calendar::event(
                $row->title,
                false,
                new \DateTime($row->start_date),
                new \DateTime($row->end_date),
                $row->id,
                [
                    'color' => $row->color,
                ]
            );
        }
        $calendar = \Calendar::addEvents($event);
        $avatars = auth()->user()->getMedia('avatar');
        return view('frontend.profile', compact('avatars', 'calendar') ,['user' => auth()->user()] );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = auth()->user();
        $user->addMedia($request->avatar)->toMediaCollection('avatar');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/BackEnd/BackEndController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BackEndController extends Controller
{
    function __construct()
    {
        $this->middleware('auth');
    }
    public function index(){
        return view('backend.index');
    }
}

app/Http/Controllers/BackEnd/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    function __construct()
    {
        $this->middleware('auth');
        $this->middleware('permission:formation-list');
        $this->middleware('permission:formation-create', ['only' => ['create','store']]);
        $this->middleware('permission:formation-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:formation-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $categories = Category::orderBy('id','DESC')->get();
        return view('backend.categories.index', compact('categories'));
    }
    public function create()
    {
        return view('backend.categories.create');
    }
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=> 'required',
            'description'=> 'required',
        ]);
        $category = new Category($request->all());
        $category->save();

        //Get translate value
        $category_name = trans('dao_custum.event');
        $add  = trans('dao_custum.add');
        $successful  = trans('dao_custum.successful');

        return redirect()->route('categories.index')->with("success", "$category_name $add $successful");
    }

    public function edit($id)
    {

    }
    public function show($id)
    {

    }
    public function destroy($id)
    {

    }
}

app/Http/Controllers/BackEnd/EventController.php
<?php

namespace App\Http\Controllers\BackEnd;

use App\Event;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use MaddHatter\LaravelFullcalendar\Calendar;
use MercurySeries\Flashy\Flashy;


class EventController extends Controller
{
    function __construct()
    {
        $this->middleware('auth');
    }
    /*function __construct()
    {
        $this->middleware('permission:event-list');
    }*/
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $event_name = trans('dao_custum.event');
        $all    = trans('dao_custum.all');
        $list = trans('dao_custum.list');

        $events = Event::orderBy('id','DESC')->get();
        $event = [];
        foreach ($events as $row){
            $enddate = $row->end_date."24:00:00";
            $event[]= \Calendar::event(
                $row->title,
                false,
                new \DateTime($row->start_date),
                new \DateTime($row->end_date),
                $row->id,
                [
                    'color' => $row->color,
                ]
            );
        }
        $calendar = \Calendar::addEvents($event);
        return view('backend.events.index', compact('events', 'calendar'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $event_name = trans('custum.event');
        $add  = trans('custum.add');

        return view('backend.events.create')->with("success", "$add $event_name");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Get translate value
        $event_name = trans('dao_custum.event');
        $add  = trans('dao_custum.add');
        $successful  = trans('dao_custum.successful');

        /*$validatation = Validator::make($request->all(), [
            'title'=> 'required',
            'color'=> 'required',
            'start_date'=> 'required',
            'end_date'=> 'required',
        ] );
        if ($validatation->fails()){
            flashy()->error('Please Insert Value');
            Flashy::error(" $please_insert_value ");
            return back();
        }*/
        $this->validate($request, [
            'title'=> 'required',
            'color'=> 'required',
            'description'=> 'required',
            'start_date'=> 'required',
            'end_date'=> 'required',
        ]);

        $event = new Event($request->all());
        $event->save();
        return redirect()->route('events.index')->with("success", "$event_name $add $successful");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $event = Event::find($id);
        return view('backend.events.show')->with('event', $event);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $event = Event::find($id);
        return view('backend.events.edit', compact('event', 'id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, event $event)
    {
        $event_name = trans('custum.event');
        $update  = trans('custum.update');
        $successful  = trans('custum.successful');
        $this->validate($request, [
            'title'=> 'required',
            'color'=> 'required',
            'description'=> 'required',
            'start_date'=> 'required',
            'end_date'=> 'required',
        ]);
        $title = $request->input('title');
        $event->update($request->all());
        return redirect()->route('events.index')->with("success", "$event_name : $title  $update $successful");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(event $event)
    {
        //get Translate Resources
        $event_name = trans('dao_custum.event');
        $delete  = trans('dao_custum.delete');
        $successful  = trans('custum.successful');

        $event->delete();
        return redirect()->route('events.index')->with("delete", "$event_name $delete $successful");
    }
}

resources/views/backend/users/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: KEUDEM
 * Date: 23/09/2019
 * Time: 21:15
 */?>
@extends('backend.layout')

@section('main')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>{{__('add_new_user')}}</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('users.index') }}"> {{__('back')}}</a>
            </div>
        </div>
    </div>
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> {{__('some_problem_with_input')}}<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    {!! Form::open(array('route' => 'users.store','method'=>'POST')) !!}
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Password:</strong>
                {!! Form::password('password', array('placeholder' => 'Password','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Confirm Password:</strong>
                {!! Form::password('confirm-password', array('placeholder' => 'Confirm Password','class' => 'form-control')) !!}

            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Role:</strong>
                {!! Form::select('roles[]', $roles,[], array( 'class' => 'form-control js-example-basic-multiple', 'multiple')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-success">{{__('submit')}}</button>
        </div>
    </div>
    {!! Form::close() !!}

@endsection
@section('js')
    <script type="text/javascript">
        $(document).ready(function() {
            $('.js-example-basic-multiple').select2();
        });
    </script>
@endsection

resources/views/backend/users/edit.blade.php
@extends('backend.layout')

@section('main')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit New User</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('users.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    {!! Form::model($user, ['method' => 'PATCH','route' => ['users.update', $user->id]]) !!}
    <div class="row">
        <div class="col-xs-8 col-sm-8 col-md-8">
            <div class="form-group">
                <strong>Name:</strong>
                {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-8 col-sm-8 col-md-8">
            <div class="form-group">
                <strong>Email:</strong>
                {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-8 col-sm-8 col-md-8">
            <div class="form-group">
                <strong>Password:</strong>
                {!! Form::password('password', array('placeholder' => 'Password','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-8 col-sm-8 col-md-8">
            <div class="form-group">
                <strong>Confirm Password:</strong>
                {!! Form::password('confirm-password', array('placeholder' => 'Confirm Password','class' => 'form-control')) !!}
            </div>
        </div>
        <div class="col-xs-8 col-sm-8 col-md-8">
            <div class="form-group">
                <strong>Role:</strong>
                {!! Form::select('roles[]', $roles,$userRole, array('class' => 'form-control js-example-basic-multiple','multiple')) !!}
            </div>
        </div>
        <div class="col-xs-8 col-sm-8 col-md-8 text-center">
            <button type="submit" class="btn btn-primary">{{__('send')}}</button>
        </div>
    </div>
    {!! Form::close() !!}

@endsection
@section('js')
    <script type="text/javascript">
        $(document).ready(function() {
            $('.js-example-basic-multiple').select2();
        });
    </script>
@endsection

resources/views/backend/users/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: KEUDEM
 * Date: 23/09/2019
 * Time: 21:08
 */?>
@extends('backend.layout')
@section('main')
    <section class="content">
        <div class="container-fluid">
            <div class="row mb-3">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        @can('user-create')
                            <a class="btn btn-success" href="{{ route('users.create') }}">{{__('new')}}</a>
                        @endcan
                    </div>

                </div>
            </div>

            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif

            <table class="table table-striped table-bordered table-hover" id="myTab">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Birth Place</th>
                        <th>Birth Date</th>
                        <th>{{__('phone')}}</th>
                        <th>{{__('gender')}}</th>
                        <th>Roles</th>
                        <th>{{__('state')}}</th>
                        <th >{{__('global.create')}}</th>
                        <th width="200px">Action</th>

                    </tr>
                </thead>
                <tbody>
                @foreach ($data as $key => $user)
                    <tr>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->birth_place }}</td>
                        <td>{{ $user->birth_date }}</td>
                        <td>{{ $user->phone_number }}</td>
                        <td>{{ $user->gender }}</td>

                        <td>
                            @if(!empty($user->getRoleNames()))
                                @foreach($user->getRoleNames() as $v)
                                    <label class="badge badge-success">{{ $v }}</label>
                                @endforeach
                            @endif
                        </td>
                        <td>
                            {{--<input data-id="{{$user->id}}" class="toggle-class" type="checkbox" data-onstyle="success" data-offstyle="danger" data-toggle="toggle" data-on="Active" data-off="InActive" {{ $user->state ? 'checked' : '' }}>--}}
                            <!-- todo: have problem in mobile device -->
                                <input class="statusChange" id="statusChange" type="checkbox" data-pk="{{$user->id}}" @if($user->state) checked @endif data-toggle="toggle" data-on="<i class='fa fa-check-circle'></i>" data-off="<i class='fa fa-ban'></i>" data-onstyle="success" data-offstyle="danger">
                        </td>
                        <td>{{ $user->created_at->diffForHumans() }}</td>
                        <td>
                            <a class="btn btn-info" href="{{ route('users.show',$user->id) }}" title="{{ __('show') }}"><i class="fa fa-eye"></i> </a>
                            @hasrole('admin')
                                <a class="btn btn-primary" href="{{ route('users.edit',$user->id) }}"  title="{{ __('edit') }}"><i class="fa fa-edit"></i></a>
                            <div class="btn-group">
                                <form  class="myAction" method="POST" action="{{URL::route('users.destroy', $user->id)}}">
                                    @csrf
                                    <input name="_method" type="hidden" value="DELETE">
                                    <button type="submit" class="btn btn-danger " title="{{ __('delete') }}">
                                        <i class="fa fa-fw fa-trash"></i>
                                    </button>
                                </form>
                            </div>
                            @endhasrole
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </section>
@endsection
@section('js')
    <script>
        $(function() {
            $('#statusChange').change(function() {
                var state = $(this).prop('checked') == true ? 1 : 0;
                var user_id = $(this).data('id');
                alert(state);

                $.ajax({
                    type: "GET",
                    dataType: "json",
                    url: '/users.changeStatus',
                    data: {'state': state, 'user_id': user_id},
                    success: function(data){
                        console.log(data.success);
                        toastr.options.closeButton = true;
                        toastr.options.closeMethod = 'fadeOut';
                        toastr.options.closeDuration = 100;
                        toastr.success(data.message);
                    }
                });
            })
        })
    </script>
    <script>
        $(document).ready( function () {
            $('#myTab').DataTable()
        });
    </script>

@endsection

resources/views/backend/users/show.blade.php
@extends('backend.layout')

@section('main')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show User</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('users.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $user->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $user->email }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Roles:</strong>
                @if(!empty($user->getRoleNames()))
                    @foreach($user->getRoleNames() as $v)
                        <label class="badge badge-success">{{ $v }}</label>
                    @endforeach
                @endif
            </div>
        </div>
    </div>
@endsection